from __future__ import annotations

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from manim import Circle, Text, VGroup

from phyanim.core.animation import PhysicsAnimation
from phyanim.core.objects import PhysicObject2D, PointParticle, object2d
from phyanim.core.state import Parameter, StateVariable
from phyanim.core.segment import PhysicsSegment
from phyanim.core.events import (
    EventCondition,
    PhysicsEvent,
    StateTransition,
    time_countdown_event,
)
from phyanim.core.enhance.annotation import (
    Annotation,
    AnnotationActivation,
    ArrowContent,
    MathTexContent,
    TextContent,
)
from phyanim.core.enhance.trigger import CrossingTrigger, Trigger
from phyanim.core.enhance.transition import Transition
from phyanim.core.enhance.timewrapper import TimeWrapper
from phyanim.core.entity.TwoD import (
    Block,
    CircularArcTrack,
    ConcaveTrack,
    ConvexTrack,
    InclinedPlane,
    LeftSemicircleTrack,
    Pulley,
    RightSemicircleTrack,
    Spring,
    StraightTrack,
    StraightTrackGroup,
    VectorArrow,
)
from phyanim.render import PhyAnimationMultiLayerScene2D

def build_animation() -> PhysicsAnimation:
    """Auto-generated by phyanim.llm.DSLParser."""

    animation = PhysicsAnimation(
        global_parameters={"m1": 1.0, "m2": 1.0, "k": 10.0, "L": 2.0},
        engine="scipy",
        sample_dt=0.01667,
    )

    # --- object "ball1" (object2d) ---
    ball1 = object2d(
        "ball1",
        states={"x1": "x1", "y1": "y1", "v1": "v1", "vy1": "vy1"},
        cartesian_position=[["x1", "y1"]],
        mobject=Circle(color="red", radius=0.2),
    )
    animation.add_object(ball1, {"x1": -1.0, "y1": 0.0, "v1": 1.0, "vy1": 0.0})

    # --- object "ball2" (object2d) ---
    ball2 = object2d(
        "ball2",
        states={"x2": "x2", "y2": "y2", "v2": "v2", "vy2": "vy2"},
        cartesian_position=[["x2", "y2"]],
        mobject=Circle(color="blue", radius=0.2),
    )
    animation.add_object(ball2, {"x2": 1.0, "y2": 0.0, "v2": -1.0, "vy2": 0.0})

    # --- object "spring" (object2d) ---
    spring = object2d(
        "spring",
        states={},
        cartesian_position=[["x1", "y1"], ["x2", "y2"]],
        mobject=Spring(start=[-1, 0], end=[1, 0], coils=10, radius=0.2, color="green", stroke_width=3),
    )
    animation.add_object(spring, {})

    # --- segment "main" ---
    animation.add_segment(
        PhysicsSegment(
            segment_id="main",
            object_ids=["ball1", "ball2", "spring"],
            state_vector=["x1", "v1", "y1", "vy1", "x2", "v2", "y2", "vy2"],
            equations={"x1": "v1", "v1": "-(k/m1)*(L - x2 + x1)", "y1": "0", "vy1": "0", "x2": "v2", "v2": "(k/m2)*(L - x2 + x1)", "y2": "0", "vy2": "0"},
            derived_equations={"spring_mid_x": "(x1 + x2)/2", "spring_mid_y": "(y1 + y2)/2"},
            state_owners={"x1": "ball1", "y1": "ball1", "v1": "ball1", "vy1": "ball1", "x2": "ball2", "y2": "ball2", "v2": "ball2", "vy2": "ball2"},
            duration=100,
        ),
        end_event=time_countdown_event(10, name="main_countdown"),
    )

    physics_layer = animation.get_physics_layer()
    # annotation "collision_text"
    physics_layer.add_annotation(
        Annotation(
            id="collision_text",
            ann_type="while",
            content=TextContent(txt="spring collision", pos_variables=["spring_mid_x", "spring_mid_y"], font_size=24),
            activation=AnnotationActivation(trigger=Trigger(expression="t > 0")),
        )
    )

    return animation

if __name__ == "__main__":
    scene = PhyAnimationMultiLayerScene2D()
    scene.set_animation(build_animation())
    scene.render()
