"""DSL → executable Python code generator.

``DSLParser.parse(dsl)`` returns a string of Python source code that, when
written to a file and executed with ``python <file>.py``, renders the physics
animation via manim — exactly mirroring the hand-written ``examples/*.py``.

The generated code is deliberately readable: each DSL element maps to one or a
few API calls, with comments grouping sections. This makes LLM output auditable
and debuggable.
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any


# Header imports + bootstrap, identical structure to examples/*.py.
_HEADER = """\
from __future__ import annotations

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from manim import Circle, Text, VGroup

from phyanim.core.animation import PhysicsAnimation
from phyanim.core.objects import PhysicObject2D, PointParticle, object2d
from phyanim.core.state import Parameter, StateVariable
from phyanim.core.segment import PhysicsSegment
from phyanim.core.events import (
    EventCondition,
    PhysicsEvent,
    StateTransition,
    time_countdown_event,
)
from phyanim.core.enhance.annotation import (
    Annotation,
    AnnotationActivation,
    ArrowContent,
    MathTexContent,
    TextContent,
)
from phyanim.core.enhance.trigger import CrossingTrigger, Trigger
from phyanim.core.enhance.transition import Transition
from phyanim.core.enhance.timewrapper import TimeWrapper
from phyanim.core.entity.TwoD import (
    Block,
    CircularArcTrack,
    ConcaveTrack,
    ConvexTrack,
    InclinedPlane,
    LeftSemicircleTrack,
    Pulley,
    RightSemicircleTrack,
    Spring,
    StraightTrack,
    StraightTrackGroup,
    VectorArrow,
)
from phyanim.render import PhyAnimationMultiLayerScene2D

"""

_FOOTER = """
if __name__ == "__main__":
    scene = PhyAnimationMultiLayerScene2D()
    scene.set_animation(build_animation())
    scene.render()
"""


class DSLParser:
    """Translate a validated DSL dict into executable Python source code."""

    def parse(self, dsl: dict[str, Any]) -> str:
        """Return the full Python source as a string."""
        body = self._build_body(dsl)
        return _HEADER + "def build_animation() -> PhysicsAnimation:\n" + body + _FOOTER

    def parse_to_file(self, dsl: dict[str, Any], path: str | Path) -> Path:
        """Write the generated source to ``path`` and return the path."""
        output_path = Path(path)
        output_path.parent.mkdir(parents=True, exist_ok=True)
        output_path.write_text(self.parse(dsl), encoding="utf-8")
        return output_path

    # ------------------------------------------------------------------
    # Body assembly
    # ------------------------------------------------------------------

    def _build_body(self, dsl: dict[str, Any]) -> str:
        lines: list[str] = []
        lines.append('    """Auto-generated by phyanim.llm.DSLParser."""')
        lines.append("")

        scene = dsl.get("scene", {})
        engine = scene.get("engine", "scipy")
        sample_dt = scene.get("sample_dt", 1 / 60)
        global_params = dsl.get("global_parameters", {})

        lines.append("    animation = PhysicsAnimation(")
        lines.append(f"        global_parameters={self._py(global_params)},")
        lines.append(f"        engine={self._py(engine)},")
        lines.append(f"        sample_dt={self._py(sample_dt)},")
        lines.append("    )")
        lines.append("")

        # Objects.
        initial_states_map = dsl.get("initial_states", {})
        for obj in dsl.get("objects", []):
            obj_id = obj["id"]
            initial = initial_states_map.get(obj_id, {})
            lines.extend(self._build_object(obj, initial))
            lines.append("")

        # Segments.
        for seg in dsl.get("segments", []):
            lines.extend(self._build_segment(seg))
            lines.append("")

        # Physics layer.
        physics_layer = dsl.get("physics_layer") or {}
        if physics_layer.get("annotations") or physics_layer.get("transitions"):
            lines.append("    physics_layer = animation.get_physics_layer()")
            for ann in physics_layer.get("annotations", []) or []:
                lines.extend(self._build_annotation(ann, indent="    "))
            for tr in physics_layer.get("transitions", []) or []:
                lines.extend(self._build_transition(tr, indent="    "))
            lines.append("")

        # Render layer.
        render_layer = dsl.get("render_layer") or {}
        sub_animations = render_layer.get("sub_animations", []) or []
        if sub_animations:
            lines.append("    render_layer = animation.get_render_layer()")
            for sub in sub_animations:
                lines.extend(self._build_sub_animation(sub, indent="    "))
            lines.append("")

        lines.append("    return animation")
        return "\n".join(lines) + "\n"

    # ------------------------------------------------------------------
    # Objects
    # ------------------------------------------------------------------

    def _build_object(self, obj: dict[str, Any], initial_state: dict[str, Any]) -> list[str]:
        lines: list[str] = []
        obj_id = obj["id"]
        obj_type = obj.get("type", "object2d")
        geometry = obj.get("geometry", "circle")
        geometry_params = obj.get("geometry_params", {})
        cart_pos = obj.get("cartesian_position", [])
        parameters = obj.get("parameters", {})
        comment = f'    # --- object "{obj_id}" ({obj_type}) ---'
        lines.append(comment)

        mobject_expr = self._build_mobject(geometry, geometry_params)
        cart_pairs = [list(pair) for pair in cart_pos]

        if obj_type == "point_particle":
            state_names = obj.get("state_names") or {}
            mass = obj.get("mass", 1.0)
            charge = obj.get("charge")
            radius = obj.get("radius", 0.1)
            color = obj.get("color", "red")
            # Auto-generate unique parameter symbol names per object so that
            # multiple point particles never collide on the default "m"/"q"
            # symbols in the global SymbolRegistry. The DSL author may override
            # via the explicit "parameters" field.
            param_names: dict[str, str] = {}
            parameters = obj.get("parameters", {})
            if parameters:
                # Author-declared parameters take their own names verbatim.
                param_names = {name: name for name in parameters}
            else:
                param_names = {"mass": f"{obj_id}_m"}
                if charge is not None:
                    param_names["charge"] = f"{obj_id}_q"
            kwargs: list[str] = [
                f'        object_id={self._py(obj_id)},',
                f"        mass={self._py(mass)},",
            ]
            if charge is not None:
                kwargs.append(f"        charge={self._py(charge)},")
            kwargs.append(f"        radius={self._py(radius)},")
            kwargs.append(f"        color={self._py(color)},")
            if state_names:
                kwargs.append(f"        state_names={self._py(state_names)},")
            if cart_pairs:
                # PointParticle takes a single tuple, not a list of tuples.
                if len(cart_pairs) == 1:
                    kwargs.append(
                        f"        cartesian_position={self._py(tuple(cart_pairs[0]))},"
                    )
                else:
                    kwargs.append(
                        f"        cartesian_position={self._py([tuple(p) for p in cart_pairs])},"
                    )
            kwargs.append(f"        parameter_names={self._py(param_names)},")
            if mobject_expr:
                kwargs.append(f"        mobject={mobject_expr},")
            lines.append(f"    {obj_id} = PointParticle(")
            lines.extend(kwargs)
            lines.append("    )")
        else:
            # object2d: use the object2d factory which accepts plain string states.
            states = obj.get("states", [])
            lines.append(f"    {obj_id} = object2d(")
            lines.append(f"        {self._py(obj_id)},")
            # object2d signature: object2d(id, *, states, parameters, cartesian_position, mobject)
            states_dict = {name: name for name in states}
            lines.append(f"        states={self._py(states_dict)},")
            if parameters:
                # object2d accepts {name: float|Parameter}; pass raw floats.
                raw_params = {}
                for name, spec in parameters.items():
                    raw_params[name] = spec["value"] if isinstance(spec, dict) else float(spec)
                lines.append(f"        parameters={self._py(raw_params)},")
            if cart_pairs:
                lines.append(
                    f"        cartesian_position={self._py([tuple(p) for p in cart_pairs])},"
                )
            if mobject_expr:
                lines.append(f"        mobject={mobject_expr},")
            lines.append("    )")

        # Initial state.
        if initial_state:
            lines.append(
                f"    animation.add_object({obj_id}, {self._py(initial_state)})"
            )
        else:
            lines.append(f"    animation.add_object({obj_id}, {{}})")
        return lines

    # ------------------------------------------------------------------
    # Geometry → mobject expression
    # ------------------------------------------------------------------

    def _build_mobject(self, geometry: str, params: dict[str, Any]) -> str:
        p = dict(params)
        if geometry == "none":
            return ""
        if geometry == "circle":
            color = self._py(p.get("color", "red"))
            radius = self._py(p.get("radius", 0.1))
            return f"Circle(color={color}, radius={radius})"
        if geometry == "text_plus":
            color = self._py(p.get("color", "red"))
            radius = self._py(p.get("radius", 0.12))
            font_size = self._py(p.get("font_size", 36))
            return (
                f'VGroup(Text("+", color={color}, font_size={font_size}), '
                f"Circle(radius={radius}, color={color}))"
            )
        if geometry == "spring":
            start = self._py(p.get("start", [-1, 0]))
            end = self._py(p.get("end", [1, 0]))
            coils = self._py(p.get("coils", 10))
            radius = self._py(p.get("radius", 0.2))
            color = self._py(p.get("color", "white"))
            stroke_width = self._py(p.get("stroke_width", 2))
            return (
                f"Spring(start={start}, end={end}, coils={coils}, radius={radius}, "
                f"color={color}, stroke_width={stroke_width})"
            )
        if geometry == "straight_track":
            start = self._py(p.get("start", [0, 0, 0]))
            end = self._py(p.get("end", [1, 0, 0]))
            color = self._py(p.get("color", "white"))
            stroke_width = self._py(p.get("stroke_width", 5))
            fill_opacity = self._py(p.get("fill_opacity", 0.3))
            return (
                f"StraightTrack(start={start}, end={end}, color={color}, "
                f"stroke_width={stroke_width}, fill_opacity={fill_opacity})"
            )
        if geometry == "right_semicircle_track":
            radius = self._py(p.get("radius", 1.0))
            color = self._py(p.get("color", "white"))
            stroke_width = self._py(p.get("stroke_width", 4))
            upward = self._py(p.get("upward", True))
            return (
                f"RightSemicircleTrack(radius={radius}, color={color}, "
                f"stroke_width={stroke_width}, upward={upward})"
            )
        if geometry == "left_semicircle_track":
            radius = self._py(p.get("radius", 1.0))
            color = self._py(p.get("color", "white"))
            stroke_width = self._py(p.get("stroke_width", 4))
            upward = self._py(p.get("upward", True))
            return (
                f"LeftSemicircleTrack(radius={radius}, color={color}, "
                f"stroke_width={stroke_width}, upward={upward})"
            )
        if geometry == "circular_arc_track":
            radius = self._py(p.get("radius", 1.0))
            start_angle = self._py(p.get("start_angle", 0))
            end_angle = self._py(p.get("end_angle", 3.141592653589793))
            color = self._py(p.get("color", "white"))
            stroke_width = self._py(p.get("stroke_width", 4))
            return (
                f"CircularArcTrack(radius={radius}, start_angle={start_angle}, "
                f"end_angle={end_angle}, color={color}, stroke_width={stroke_width})"
            )
        if geometry == "concave_track":
            width = self._py(p.get("width", 4.0))
            height = self._py(p.get("height", 2.0))
            radius = self._py(p.get("radius", 1.0))
            color = self._py(p.get("color", "white"))
            stroke_width = self._py(p.get("stroke_width", 2))
            fill_opacity = self._py(p.get("fill_opacity", 0.3))
            return (
                f"ConcaveTrack(width={width}, height={height}, radius={radius}, "
                f"color={color}, stroke_width={stroke_width}, fill_opacity={fill_opacity})"
            )
        if geometry == "convex_track":
            radius = self._py(p.get("radius", 1.0))
            color = self._py(p.get("color", "white"))
            stroke_width = self._py(p.get("stroke_width", 2))
            fill_opacity = self._py(p.get("fill_opacity", 0.3))
            return (
                f"ConvexTrack(radius={radius}, color={color}, "
                f"stroke_width={stroke_width}, fill_opacity={fill_opacity})"
            )
        if geometry == "inclined_plane":
            length = self._py(p.get("length", 3.0))
            angle = self._py(p.get("angle", 0.5235987755982988))
            color = self._py(p.get("color", "white"))
            stroke_width = self._py(p.get("stroke_width", 3))
            fill_opacity = self._py(p.get("fill_opacity", 0.12))
            return (
                f"InclinedPlane(length={length}, angle={angle}, color={color}, "
                f"stroke_width={stroke_width}, fill_opacity={fill_opacity})"
            )
        if geometry == "pulley":
            radius = self._py(p.get("radius", 0.25))
            color = self._py(p.get("color", "white"))
            stroke_width = self._py(p.get("stroke_width", 3))
            return f"Pulley(radius={radius}, color={color}, stroke_width={stroke_width})"
        if geometry == "block":
            width = self._py(p.get("width", 0.6))
            height = self._py(p.get("height", 0.35))
            color = self._py(p.get("color", "white"))
            stroke_width = self._py(p.get("stroke_width", 3))
            fill_opacity = self._py(p.get("fill_opacity", 0.25))
            return (
                f"Block(width={width}, height={height}, color={color}, "
                f"stroke_width={stroke_width}, fill_opacity={fill_opacity})"
            )
        if geometry == "vector_arrow":
            start = self._py(p.get("start", [0, 0]))
            end = self._py(p.get("end", [1, 0]))
            color = self._py(p.get("color", "white"))
            stroke_width = self._py(p.get("stroke_width", 4))
            return (
                f"VectorArrow(start={start}, end={end}, color={color}, "
                f"stroke_width={stroke_width})"
            )
        if geometry == "straight_track_group":
            tracks = self._py(p.get("tracks", []))
            color = self._py(p.get("color", "white"))
            stroke_width = self._py(p.get("stroke_width", 2))
            return f"StraightTrackGroup(tracks={tracks}, color={color}, stroke_width={stroke_width})"
        # Fallback: plain Circle.
        return f"Circle(color={self._py('white')}, radius=0.1)"

    # ------------------------------------------------------------------
    # Segments
    # ------------------------------------------------------------------

    def _build_segment(self, seg: dict[str, Any]) -> list[str]:
        lines: list[str] = []
        seg_id = seg["id"]
        object_ids = seg["object_ids"]
        equations = seg["equations"]
        owners = seg.get("owners") or {}
        parameters = seg.get("parameters", {})
        derived = seg.get("derived", {})
        duration = seg.get("duration", 100)
        end_event = seg["end_event"]

        lines.append(f'    # --- segment "{seg_id}" ---')

        # If single object and no owners, infer them.
        if not owners and len(object_ids) == 1:
            owners = {name: object_ids[0] for name in equations}

        lines.append("    animation.add_segment(")
        lines.append("        PhysicsSegment(")
        lines.append(f"            segment_id={self._py(seg_id)},")
        lines.append(f"            object_ids={self._py(object_ids)},")
        lines.append(f"            state_vector={self._py(list(equations.keys()))},")
        lines.append(f"            equations={self._py(equations)},")
        if derived:
            lines.append(f"            derived_equations={self._py(derived)},")
        lines.append(f"            state_owners={self._py(owners)},")
        if parameters:
            lines.append(f"            parameters={self._py(parameters)},")
        lines.append(f"            duration={self._py(duration)},")
        lines.append("        ),")
        lines.append(f"        end_event={self._build_end_event(end_event, seg_id)},")
        lines.append("    )")
        return lines

    def _build_end_event(self, end_event: dict[str, Any], seg_id: str) -> str:
        if end_event.get("type") == "countdown":
            value = end_event["value"]
            name = end_event.get("name", f"{seg_id}_countdown")
            return f"time_countdown_event({self._py(value)}, name={self._py(name)})"

        expression = end_event["expression"]
        direction = end_event.get("direction", 0)
        transition = end_event.get("transition") or {}
        event_name = end_event.get("name", f"{seg_id}_end")

        if transition:
            trans_name = f"{event_name}_transition"
            transition_expr = (
                f"StateTransition.from_equations({self._py(trans_name)}, {self._py(transition)})"
            )
            return (
                f"PhysicsEvent.terminal({self._py(event_name)}, {self._py(expression)}, "
                f"direction={self._py(direction)}, transition={transition_expr})"
            )
        # Identity transition (no transition arg).
        return (
            f"PhysicsEvent.terminal({self._py(event_name)}, {self._py(expression)}, "
            f"direction={self._py(direction)})"
        )

    # ------------------------------------------------------------------
    # Annotations
    # ------------------------------------------------------------------

    def _build_annotation(self, ann: dict[str, Any], indent: str) -> list[str]:
        lines: list[str] = []
        ann_id = ann["id"]
        ann_type = ann["type"]
        content = ann["content"]
        lines.append(f"{indent}# annotation \"{ann_id}\"")
        content_expr = self._build_content(content)
        activation_expr = self._build_activation(ann)
        lines.append(f"{indent}physics_layer.add_annotation(")
        lines.append(f"{indent}    Annotation(")
        lines.append(f"{indent}        id={self._py(ann_id)},")
        lines.append(f"{indent}        ann_type={self._py(ann_type)},")
        lines.append(f"{indent}        content={content_expr},")
        lines.append(f"{indent}        activation={activation_expr},")
        lines.append(f"{indent}    )")
        lines.append(f"{indent})")
        return lines

    def _build_content(self, content: dict[str, Any]) -> str:
        kind = content["kind"]
        pos = content["pos_variables"]
        if kind == "arrow":
            shift = content["shift_variables"]
            scale = content.get("scale", 1.0)
            color = content.get("color", "red")
            tip_length = content.get("tip_length", 0.15)
            max_ratio = content.get("max_stroke_width_to_length_ratio", 2)
            return (
                f"ArrowContent(pos_variables={self._py(tuple(pos))}, "
                f"shift_variables={self._py(tuple(shift))}, scale={self._py(scale)}, "
                f"color={self._py(color)}, tip_length={self._py(tip_length)}, "
                f"max_stroke_width_to_length_ratio={self._py(max_ratio)})"
            )
        if kind == "text":
            text = content["text"]
            font_size = content.get("font_size", 24)
            return (
                f"TextContent(txt={self._py(text)}, "
                f"pos_variables={self._py(tuple(pos))}, font_size={self._py(font_size)})"
            )
        if kind == "mathtex":
            tex_strings = content.get("tex_strings") or [content["text"]]
            return (
                f"MathTexContent(tex_strings={self._py(list(tex_strings))}, "
                f"pos_variables={self._py(tuple(pos))})"
            )
        return f"TextContent(txt='', pos_variables={self._py(tuple(pos))})"

    def _build_activation(self, ann: dict[str, Any]) -> str:
        ann_type = ann["type"]
        if ann_type == "while":
            trigger = ann["trigger"]
            return f"AnnotationActivation(trigger={self._build_trigger(trigger)})"
        if ann_type == "time_range":
            trigger = ann["trigger"]
            advance = ann.get("advance", 0.0)
            delay = ann.get("delay", 0.0)
            return (
                f"AnnotationActivation(trigger={self._build_trigger(trigger)}, "
                f"advance={self._py(advance)}, delay={self._py(delay)})"
            )
        if ann_type == "between":
            start_trigger = ann["start_trigger"]
            end_trigger = ann["end_trigger"]
            return (
                f"AnnotationActivation(start_trigger={self._build_trigger(start_trigger)}, "
                f"end_trigger={self._build_trigger(end_trigger)})"
            )
        return "AnnotationActivation()"

    def _build_trigger(self, trigger: dict[str, Any]) -> str:
        expression = trigger["expression"]
        direction = trigger.get("direction", 0)
        # direction=0 → plain Trigger; nonzero → CrossingTrigger for zero-crossing precision.
        if direction == 0:
            return f"Trigger(expression={self._py(expression)})"
        return f"CrossingTrigger(expression={self._py(expression)}, direction={self._py(direction)})"

    # ------------------------------------------------------------------
    # Transitions (formula derivations)
    # ------------------------------------------------------------------

    def _build_transition(self, tr: dict[str, Any], indent: str) -> list[str]:
        lines: list[str] = []
        tr_id = tr["id"]
        groups = tr["groups"]
        triggers = tr["triggers"]
        pos = tr["pos_variables"]
        group_dir = tr.get("group_dir", {})
        style = tr.get("style", "scale")
        duration = tr.get("duration", 0.5)
        font_size = tr.get("font_size", 24)

        triggers_expr = "[" + ", ".join(self._build_trigger(t) for t in triggers) + "]"
        lines.append(f"{indent}# transition \"{tr_id}\"")
        lines.append(f"{indent}physics_layer.add_transition(")
        lines.append(f"{indent}    Transition(")
        lines.append(f"{indent}        id={self._py(tr_id)},")
        lines.append(f"{indent}        group_strings={self._py(groups)},")
        lines.append(f"{indent}        triggers={triggers_expr},")
        lines.append(f"{indent}        pos_variables={self._py(tuple(pos))},")
        lines.append(f"{indent}        group_dir={self._py(group_dir)},")
        lines.append(f"{indent}        font_size={self._py(font_size)},")
        lines.append(f"{indent}        style={self._py(style)},")
        lines.append(f"{indent}        duration={self._py(duration)},")
        lines.append(f"{indent}    )")
        lines.append(f"{indent})")
        return lines

    # ------------------------------------------------------------------
    # Render layer sub-animations
    # ------------------------------------------------------------------

    def _build_sub_animation(self, sub: dict[str, Any], indent: str) -> list[str]:
        lines: list[str] = []
        wrapper = sub["time_wrapper"]
        wrapper_id = wrapper["id"]
        wrapper_type = wrapper["type"]
        trigger = wrapper["trigger"]

        trigger_expr = self._build_trigger(trigger)
        wrapper_kwargs: list[str] = [
            f"id={self._py(wrapper_id)}",
            f"type={self._py(wrapper_type)}",
            f"trigger={trigger_expr}",
        ]
        if wrapper_type == "freeze":
            wrapper_kwargs.append(f"extend_to={self._py(wrapper['extend_to'])}")
        elif wrapper_type == "slow":
            wrapper_kwargs.append(f"speed={self._py(wrapper.get('speed', 0.5))}")
            if "advance" in wrapper:
                wrapper_kwargs.append(f"advance={self._py(wrapper['advance'])}")
            if "delay" in wrapper:
                wrapper_kwargs.append(f"delay={self._py(wrapper['delay'])}")

        wrapper_expr = f"TimeWrapper({', '.join(wrapper_kwargs)})"

        annotations = sub.get("annotations", []) or []
        transitions = sub.get("transitions", []) or []

        lines.append(f"{indent}# sub_animation \"{wrapper_id}\"")

        if not annotations and not transitions:
            lines.append(f"{indent}render_layer.add_sub_animation(")
            lines.append(f"{indent}    time_wrapper={wrapper_expr},")
            lines.append(f"{indent})")
            return lines

        # Build annotation list literal inline.
        ann_exprs: list[str] = []
        for ann in annotations:
            content_expr = self._build_content(ann["content"])
            activation_expr = self._build_activation(ann)
            ann_exprs.append(
                f"Annotation(id={self._py(ann['id'])}, ann_type={self._py(ann['type'])}, "
                f"content={content_expr}, activation={activation_expr})"
            )
        ann_list = "[" + ", ".join(ann_exprs) + "]" if ann_exprs else "[]"

        # Build transition list literal inline.
        tr_exprs: list[str] = []
        for tr in transitions:
            triggers = tr["triggers"]
            triggers_expr = "[" + ", ".join(self._build_trigger(t) for t in triggers) + "]"
            tr_exprs.append(
                f"Transition(id={self._py(tr['id'])}, group_strings={self._py(tr['groups'])}, "
                f"triggers={triggers_expr}, pos_variables={self._py(tuple(tr['pos_variables']))}, "
                f"group_dir={self._py(tr.get('group_dir', {}))}, "
                f"font_size={self._py(tr.get('font_size', 24))}, "
                f"style={self._py(tr.get('style', 'scale'))}, "
                f"duration={self._py(tr.get('duration', 0.5))})"
            )
        tr_list = "[" + ", ".join(tr_exprs) + "]" if tr_exprs else "[]"

        lines.append(f"{indent}render_layer.add_sub_animation(")
        lines.append(f"{indent}    time_wrapper={wrapper_expr},")
        lines.append(f"{indent}    annotations={ann_list},")
        lines.append(f"{indent}    transitions={tr_list},")
        lines.append(f"{indent})")
        return lines

    # ------------------------------------------------------------------
    # Helpers
    # ------------------------------------------------------------------

    def _py(self, value: Any) -> str:
        """Serialize a Python value into its literal source representation."""
        return json.dumps(value, ensure_ascii=False)


__all__ = ["DSLParser"]
